[package]
name = "regview"
version = "0.1.0"
edition = "2018"
description = "Offline-viewer for registry files"
homepage = "https://www.github.com/janstarke/regview"
license-file = "LICENSE"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
clap = "3"
simplelog = "0.11"
log = "0.4"
cursive = "0.16"
cursive-aligned-view = "^0"
cursive_table_view = "0.13"
rwinreg = { git = "https://github.com/janstarke/r-winreg.git", branch="feature/winstructs", version="0.2.0-janstarke.2" }